version: '3.8'
services:

  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - '27017:27017'

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_USER: user
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3306:3306"

  config-server:
    build:
      context: ./ConfigurationServer/configurationServer
      dockerfile: Dockerfile
    ports:
      - "7077:7077"
    expose:
      - '7077'
    healthcheck:
      interval: 10s
      retries: 4

  eureka-server:
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - '8761'

  gateway-server:
    build:
      context: ./GatewayServere/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - config-server

  stock:
    build:
      context: ./StockMS/StockMS/
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    expose:
      - '9099'
    depends_on:
      - config-server
    environment:
      - CONFIG_SERVICE_URL=http://config-server:7077
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka
      - mongoDB
      - broker
    links:
      - mongoDB
    restart: on-failure
   # restart: on-failure

  category:
    build:
      context: ./Category/Category
      dockerfile: Dockerfile
    ports:
      - "6066:6066"
    environment:
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka
    depends_on:
      - broker
    links:
      - mongoDB

  product:
    build:
      context: ./ProductMS/ProductMS
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVICE_URL=http://config-server:7077
    depends_on:
      - broker
      - mysql
      - config-server


  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1




